In [1]:
import numpy as np

In [3]:
a=np.arange(1,11,1)

In [4]:
b=a

In [5]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(a+b)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
print(sum(a))

55
