In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)

In [4]:
b=np.copy(a)

In [5]:
b[[0,-1]]=b[[-1,0]]

In [6]:
print(f"Original array\n\n {a}")

Original array

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
print(f"Swapped array\n\n {b}")

Swapped array

 [[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
