In [1]:
import numpy as np

In [2]:
a=np.arange(1,11,1)

In [3]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
b=np.arange(2,12,1)

In [5]:
print(b)

[ 2  3  4  5  6  7  8  9 10 11]


In [6]:
print(a*b)

[  2   6  12  20  30  42  56  72  90 110]
