In [1]:
import numpy as np

In [2]:
a=np.matrix('1 2; 3 4')
b=np.matrix('5 6; 7 8')
np.dot(a, b)

matrix([[19, 22],
        [43, 50]])

In [3]:
m=np.matrix('1 2;3 4')
m.T

matrix([[1, 3],
        [2, 4]])

In [4]:
a.trace()

matrix([[5]])

In [5]:
np.linalg.matrix_rank(a)

2

In [6]:
np.linalg.inv(a)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [7]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 matrix([[-0.82456484, -0.41597356],
         [ 0.56576746, -0.90937671]]))